Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ARM_Hotel.Models
{
    public class Photo
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }  
        public int? ApartmentId { get; set; }
        public Apartment Apartment { get; set; }
        public string Description { get; set; }
        public string Filename { get; set; }

    }
}

Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ARM_Hotel.Models;

namespace ARM_Hotel.Controllers
{
    public class PhotosController : Controller
    {
        private HotelDBEntities db = new HotelDBEntities();

        // GET: Photos
        public ActionResult Index()
        {
            var photos = db.Photos.Include(p => p.Apartment);
            return View(photos.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            ViewBag.ApartmentId = new SelectList(db.Apartments, "Id", "Type");
            return View();
        }

        // POST: Photos/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Photography,ApartmentId")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApartmentId = new SelectList(db.Apartments, "Id", "Type", photo.ApartmentId);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApartmentId = new SelectList(db.Apartments, "Id", "Type", photo.ApartmentId);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Photography,ApartmentId")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApartmentId = new SelectList(db.Apartments, "Id", "Type", photo.ApartmentId);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Photos/AddPhoto.cshtml
@model ARM_Hotel.Models.Photo
@{
    ViewBag.Title = "AddPhoto";
}
<h2>AddPhoto</h2>
@using (Html.BeginForm("AddPhoto", "Photos", FormMethod.Post, new
{
    enctype ="multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id", Model.PhotoId);
    <div class="form-horizontal">
        <h4>MoviePhoto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Назване фильма", htmlAttributes: new
            {
                @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(Model.Title, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Описание", htmlAttributes: new { @class = "control-label col-md2" })
            <div class="col-md-10">
                @Html.Editor("description", new { htmlAttributes = new { @class = "formcontrol" } })
                @Html.ValidationMessage("description", "", new
                {
                    @class = "text-danger"
               })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" name="upload" /><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Загрузить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Вернуться к списку фотографий", "Index")
</div>

Views/Photos/Create.cshtml
@model ARM_Hotel.Models.Photo

@{
    ViewBag.Title = "Добавление фотографии";
}

<h2>Добавление новой фотографии</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Photography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApartmentId, "ApartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку фотографий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photos/Delete.cshtml
@model ARM_Hotel.Models.Photo

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление фотографии</h2>

<h3>Вы действительно хотите удалить выбранное фото?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apartment.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apartment.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photography)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку фотографий", "Index")
        </div>
    }
</div>

Views/Photos/Details.cshtml
@model ARM_Hotel.Models.Photo

@{
    ViewBag.Title = "Детальная информация о фотографии";
}

<h2>Подробная информация о фотографии</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apartment.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apartment.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photography)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться к списку фотографий", "Index")
</p>

Views/Photos/Edit.cshtml
@model ARM_Hotel.Models.Photo

@{
    ViewBag.Title = "Редактирование информации о фото";
}

<h2>Редактирование информации о фото</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Photography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApartmentId, "ApartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку фотографий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photos/Index.cshtml
@model IEnumerable<ARM_Hotel.Models.Photo>

@{
    ViewBag.Title = "Фотографии";
}

<h2>Список фотографий</h2>

<p>
    @Html.ActionLink("Добавить новую фотографию", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Apartment.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photography)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Apartment.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photography)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Подробности", "Details", new { id = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>