Controllers/TakeLivingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using ARM_Hotel.Models;

namespace ARM_Hotel.Controllers
{
    public class TakeLivingsController : Controller
    {
        private HotelDBEntities db = new HotelDBEntities();

        // GET: TakeLivings
        [Authorize(Roles = "Admin, Operator, Client")]
        public ActionResult Index(int? clientId, bool? isLiving)
        {
            ViewBag.IsLiving = isLiving;

            if (clientId != null)
            {
                Client client = db.Clients.Find(clientId);
                if (client == null)
                    return HttpNotFound();

                ViewBag.ClientId = clientId;
                ViewBag.Client = client;

                return View("ChooseDate");

            }

            return View(db.Clients.ToList());
        }
        [Authorize(Roles = "Admin, Operator, Client")]
        [HttpPost]
        public ActionResult Index(int clientId, bool isLiving)
        {
            Client client = db.Clients.Find(clientId);
            if (client == null)
                return HttpNotFound();

            ViewBag.ClientId = clientId;
            ViewBag.Client = client;
            ViewBag.settling = DateTime.Now.Date;
            ViewBag.eviction = DateTime.Now.Date.AddDays(1);
            ViewBag.IsLiving = isLiving;
            return View("ChooseDate");
        }

        [Authorize(Roles = "Admin, Operator, Client")]
        [HttpPost]
        public ActionResult ChooseDate(int clientId, DateTime? settling, DateTime? eviction, int guestCount, bool isLiving)
        {

            Client client = db.Clients.Find(clientId);
            if (settling < DateTime.Now.Date || settling == null)
            {
                ModelState.AddModelError("Settling", "Нельзя оформить проживание на прошедшие даты");
                ViewBag.ClientId = clientId;
                ViewBag.settling = settling;
                ViewBag.eviction = eviction;
                ViewBag.guestCount = guestCount;
                ViewBag.IsLiving = isLiving;
                ViewBag.Client = client;
                return View();
            }
            else if (eviction <= settling || eviction == null)
            {
                ModelState.AddModelError("Eviction", "Дата выселения должна быть больше даты выселения");
                ViewBag.ClientId = clientId;
                ViewBag.settling = settling;
                ViewBag.eviction = eviction;
                ViewBag.guestCount = guestCount;
                ViewBag.IsLiving = isLiving;
                ViewBag.Client = client;
                return View();
            }
            if (guestCount < 0 || guestCount > 5)
            {
                ModelState.AddModelError("GuestCount", "Число гостей должно быть от 0 до 5");
                ViewBag.ClientId = clientId;
                ViewBag.settling = settling;
                ViewBag.eviction = eviction;
                ViewBag.guestCount = guestCount;
                ViewBag.IsLiving = isLiving;
                ViewBag.Client = client;
                return View();
            }

            List<Apartment> Apartments = db.Apartments
                                    .Include(m => m.Living)
                                    .Include(n => n.Booking)
                                    .ToList();
            List<Apartment> avalibleApartment = new List<Apartment>();
            foreach (var apartment in Apartments)
            {
                if (apartment.MaxGuests >= guestCount)
                    if (!(apartment.Living.Any(l => l.Settling >= settling && l.Settling <= eviction)) &&
                        !(apartment.Living.Any(l => l.Eviction >= settling && l.Eviction <= eviction)) &&
                        !(apartment.Living.Any(l => l.Settling <= settling && l.Eviction >= eviction)) &&
                        !(apartment.Booking.Any(l => l.Settling >= settling && l.Settling <= eviction)) &&
                        !(apartment.Booking.Any(l => l.Eviction >= settling && l.Eviction <= eviction)) &&
                        !(apartment.Booking.Any(l => l.Settling <= settling && l.Eviction >= eviction)))
                    {
                        avalibleApartment.Add(apartment);
                    }
            }

            ViewBag.ClientId = clientId;
            ViewBag.settling = settling;
            ViewBag.eviction = eviction;
            ViewBag.Client = client;
            ViewBag.guestCount = guestCount;
            ViewBag.IsLiving = isLiving;
            return View("ChooseApartment", avalibleApartment);
        }

        [Authorize(Roles = "Admin, Operator, Client")]
        [HttpPost]
        public ActionResult ChooseApartment(int clientId, DateTime settling, DateTime eviction, int apartmentId, int guestCount, bool isLiving)
        {
            Client client = db.Clients.Find(clientId);
            Apartment apartment = db.Apartments.Find(apartmentId);

            decimal price = apartment.Price * Convert.ToDecimal((eviction - settling).TotalDays);

            ViewBag.ClientId = clientId;
            ViewBag.settling = settling.ToLongDateString();
            ViewBag.eviction = eviction.ToLongDateString();
            ViewBag.Client = client;
            ViewBag.Apartment = apartment;
            ViewBag.Price = price;
            ViewBag.guestCount = guestCount;
            ViewBag.IsLiving = isLiving;
            return View("ConfirmLiving");
        }

        //Services
        [Authorize(Roles = "Admin, Operator")]
        public ActionResult AddAdditionalService(int id)
        {
            Living living = db.Livings.Find(id);
            if (living == null)
                return HttpNotFound();
            return View(living);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddAdditionalService(int id, HttpPostedFileBase upload, string description)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));
                Photo photo = new Photo();
                photo.ApartmentId = id;
                photo.Filename = fileName;
                photo.Description = description;
                db.Photos.Add(photo);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Operator, Client")]
        [HttpPost]
        public ActionResult ConfirmLiving(int clientId, DateTime settling, DateTime eviction, int apartmentId, int guestCount, bool isLiving, decimal price)
        {
            Apartment apartment = db.Apartments.Find(apartmentId);

            if (isLiving)
            {
                Living living = new Living()
                {
                    ClientId = clientId,
                    Settling = settling,
                    Eviction = eviction,
                    Price = price,
                    ValueOfGuests = guestCount,
                    Active = true,
                    ApartmentId = apartmentId,
                    Type = apartment.Type,
                    Number = apartment.Number

                };
                db.Livings.Add(living);

                db.SaveChanges();

                if (guestCount > 0)
                {
                    return RedirectToAction("Create", "Guests", new { livingId = living.Id });
                }


                return RedirectToAction("Index", "Livings");
            }
            else
            {
                Booking booking = new Booking()
                {
                    ClientId = clientId,
                    Settling = settling,
                    Eviction = eviction,
                    Price = price,
                    ValueOfGuests = guestCount,
                    ApartmentId = apartmentId,
                    Type = apartment.Type,
                    Number = apartment.Number
                };
                db.Bookings.Add(booking);

                db.SaveChanges();

                if (guestCount > 0)
                {
                    return RedirectToAction("Create", "Guests", new { bookingId = booking.Id });
                }

                return RedirectToAction("Index", "Bookings");
            }

        }
    }
}

Views/TakeLivings/ChooseApartment.cshtml
@model IEnumerable<ARM_Hotel.Models.Apartment>
@{
    ViewBag.Title = "ChooseApartment";
}

<h2>Выбор свободных номеров</h2>

@using (Html.BeginForm("ChooseApartment", "TakeLivings", FormMethod.Post))
{
    if (Model.Any())
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaxGuests)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxGuests)
                    </td>
                    <td>
                        <div>
                            @Html.Hidden("ClientId", ViewBag.ClientId as string)
                            @Html.Hidden("ApartmentId", item.Id)
                            @Html.Hidden("settling", ViewBag.settling as string)
                            @Html.Hidden("eviction", ViewBag.eviction as string)
                            @Html.Hidden("guestCount", ViewBag.guestCount as string)
                            @Html.Hidden("isLiving", ViewBag.isLiving as string)
                            @Html.Hidden("Price", ViewBag.Price as string)
                            <input type="submit" value="Выбрать" class="btn btn-primary " />
                        </div>

                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <div class="form-group">
            <h3>
                Нет свободных номеров на выбранные даты. 
            </h3>
            @Html.ActionLink("Вернуться к выбору дат", "ChooseDate", "TakeLivings", null, new { @class = "btn btn-info" })
        </div>
    }

}

Views/TakeLivings/ChooseDate.cshtml

@{
    ViewBag.Title = "ChooseDate";
}

<h2>Оформление проживания: выбор даты</h2>

@using (Html.BeginForm("ChooseDate", "TakeLivings", FormMethod.Post))
{
    <div class="form-horizontal">
        @Html.Hidden("ClientId", ViewBag.GuestId as string)

        <div class="form-group">
            @Html.Label("Клиент", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(ViewBag.Client.FirstName + " " + ViewBag.Client.LastName + " " + ViewBag.Client.Patronymic as string, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Выберите дату заселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="settling" class="form-control" value="@DateTime.Now.Date.ToOADate()">
                @Html.ValidationMessage("Settling", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Выберите дату выселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="eviction" class="form-control" value="@DateTime.Now.Date.ToString()">
                @Html.ValidationMessage("Eviction", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Выберите количество гостей", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="guestCount" class="form-control" value="0">
                @Html.ValidationMessage("GuestCount", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.Hidden("isLiving", ViewBag.isLiving as string)
                <input type="submit" value="Выбрать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Views/TakeLivings/ConfirmLiving.cshtml
@{
    ViewBag.Title = "ConfirmLiving";
}
<h2>Подтверждение заселения</h2>
@using (Html.BeginForm("ConfirmLiving", "TakeLivings", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Клиент", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(ViewBag.Client.FirstName + " " + ViewBag.Client.LastName + " " + ViewBag.Client.Patronymic as string, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Номер", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(ViewBag.Apartment.Number as string, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Дата заселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="control-label">@ViewBag.settling.ToString()</label>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Дата выселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="control-label">@ViewBag.eviction.ToString()</label>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Количество гостей", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="control-label">@ViewBag.guestCount.ToString()</label>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Стоимость проживания", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(ViewBag.Price.ToString() as string, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        @Html.Hidden("ClientId", ViewBag.ClientId as string)
        @Html.Hidden("ApartmentId", ViewBag.Apartment.Id as string)
        @Html.Hidden("settling", ViewBag.settling as string)
        @Html.Hidden("eviction", ViewBag.eviction as string)
        @Html.Hidden("guestCount", ViewBag.guestCount as string)
        @Html.Hidden("isLiving", ViewBag.isLiving as string)
        @Html.Hidden("Price", ViewBag.Price as string)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Подтвердить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Views/TakeLivings/Index.cshtml
@model IEnumerable<ARM_Hotel.Models.Client>
@{
    ViewBag.Title = "Index";
}

@if (ViewBag.IsLiving == true)
{
    <h2>Оформление проживания</h2>
}
else
{
    <h2>Оформление бронирования</h2>
}

<div class="form-group">
    @Html.ActionLink("Создать нового", "Create", "Clients", null, new { @class = "btn btn-info" })
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeriaPas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberPas)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeriaPas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberPas)
            </td>
            <td>
                @using (Html.BeginForm())
                {
                    <div>
                        @Html.Hidden("ClientId", item.Id)
                        @Html.Hidden("IsLiving", true)
                        <input type="submit" value="Выбрать" class="btn btn-primary" />
                    </div>
                }
            </td>
        </tr>
    }

</table>