Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ARM_Hotel.Models
{
    public class Apartment
    {
        public int Id { get; set; }

        [Display(Name = "Номер")]
        [Required(ErrorMessage = "Введите номер")]
        [StringLength(4, MinimumLength = 1)]
        public string Number { get; set; }

        [Display(Name = "Тип номера")]
        [Required(ErrorMessage = "Введите тип номера")]
        [StringLength(50, MinimumLength = 3)]
        public string Type { get; set; }

        [Display(Name = "Стоимость")]
        [Required(ErrorMessage = "Введите цену")]
        [Range(100, 1000000)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [Display(Name = "Максимальное количество гостей")]
        [Required(ErrorMessage = "Введите максимальное количество гостей")]
        [Range(0, 15)]
        public int MaxGuests { get; set; }

        public List<Photo> Photos { get; set; }
        public List<Living> Living { get; set; }
        public List<Booking> Booking { get; set; }

        public Apartment()
        {
            Photos = new List<Photo>();
            Living = new List<Living>();
            Booking = new List<Booking>();
        }
    }
}

Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ARM_Hotel.Models;

namespace ARM_Hotel.Controllers
{
    public class ApartmentsController : Controller
    {
        private HotelDBEntities db = new HotelDBEntities();

        // GET: Apartments
        public ActionResult Index()
        {
            ViewBag.Error = "";
            return View(db.Apartments.ToList());
        }

        //Photos
        [Authorize(Roles = "Admin")]
        public ActionResult AddPhoto(int id)
        {
            Apartment apartment = db.Apartments.Find(id);
            if (apartment == null)
                return HttpNotFound();
            return View(apartment);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddPhoto(int id, HttpPostedFileBase upload, string description)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));
                Photo photo = new Photo();
                photo.ApartmentId = id;
                photo.Filename = fileName;
                photo.Description = description;
                db.Photos.Add(photo);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }



        // GET: Apartments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartment apartment = db.Apartments.Include(a => a.Photos).FirstOrDefault(a => a.Id == id);
            if (apartment == null)
            {
                return HttpNotFound();
            }
            List<byte[]> photos = new List<byte[]>();
            foreach (Photo photo in apartment.Photos)
            {
                photos.Add(System.IO.File.ReadAllBytes(Server.MapPath("~/Files/" + photo.Filename)));
            }
            ViewBag.Photos = photos;
            return View(apartment);
        }

        // GET: Apartments/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Apartments/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Number,Type,Price,MaxGuests")] Apartment apartment)
        {
            if (ModelState.IsValid)
            {

                if (db.Apartments.Any(cl => cl.Number == apartment.Number))
                {
                    if (db.Apartments.Any(cl => cl.Type == apartment.Type))
                    {
                        ModelState.AddModelError("Number", "Такой номер уже существует");
                        return View();
                    }
                }

                db.Apartments.Add(apartment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartment);
        }

        // GET: Apartments/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartment apartment = db.Apartments.Find(id);
            if (apartment == null)
            {
                return HttpNotFound();
            }
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Number,Type,Price,MaxGuests")] Apartment apartment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(apartment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(apartment);
        }

        // GET: Apartments/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartment apartment = db.Apartments.Find(id);
            if (apartment == null)
            {
                return HttpNotFound();
            }
            ViewBag.Error = "";
            if (db.Livings.Any(cl => cl.Number == apartment.Number))
            {
                DateTime dt = DateTime.Now;
                List<Living> living = db.Livings.Where(cl => cl.Number == apartment.Number).Where(cl => cl.Eviction < dt).ToList();
                if ((living.Count != 0)&&(db.Bookings.Any(cl => cl.Number == apartment.Number)))
                {
                    ViewBag.Error = "Нельзя удалить номер, пока в нём живут люди";
                }
            }
            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Apartment apartment = db.Apartments.Find(id);


            db.Apartments.Remove(apartment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Apartments/AddPhoto.cshtml
@model ARM_Hotel.Models.Apartment
@{
    ViewBag.Title = "Добавить фото";
}
<h2>Добавление фотографий @Model.Number-го номера</h2>
@using (Html.BeginForm("AddPhoto", "Apartments", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id", Model.Id);
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Номер: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(Model.Number, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Описание: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("description", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("description", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" name="upload" /><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Загрузить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Вернуться к списку номеров", "Index")
</div>

Views/Apartments/Create.cshtml
@model ARM_Hotel.Models.Apartment

@{
    ViewBag.Title = "Добавление номера";
}

<h2>Добавление нового номера</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxGuests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxGuests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxGuests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку номеров", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Apartments/Delete.cshtml
@model ARM_Hotel.Models.Apartment

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление номера</h2>

<h3>Вы уверены, что хотите удалить выбранный номер?</h3>
<p style="color: red">@ViewBag.Error</p>
<div>
    <h4>Номер @Model.Number</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxGuests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxGuests)
        </dd>
        
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @if (ViewBag.Error == "")
            {
                <input type="submit" value="Удалить" class="btn btn-default" />

            }
            @Html.ActionLink("Вернуться к списку номеров", "Index")
        </div>
    }
</div>

Views/Apartments/Details.cshtml
@model ARM_Hotel.Models.Apartment

@{
    ViewBag.Title = "Детальная информация о номере";
}

<h2>Детальная информация о номере</h2>

<div>
    <h4>Номер @Model.Number</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxGuests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxGuests)
        </dd>

        <dd>

        </dd>
    </dl>

    <div class="media">
        <div class="media-object">
            @foreach (byte[] photo in ViewBag.Photos)
            {
                <img class="d-block w-100" src="data:image/jpeg;base64,@(Convert.ToBase64String(photo))">
            }
        </div>
    </div>

    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id })
        </p>
    }
    <p>
        @Html.ActionLink("Вернуться к списку номеров", "Index")
    </p>
</div>

Views/Apartments/Edit.cshtml
@model ARM_Hotel.Models.Apartment

@{
    ViewBag.Title = "Редактирование информации о номере";
}

<h2>Редактирование информации о номере</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Номер @Model.Number</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxGuests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxGuests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxGuests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Добавить фото", "AddPhoto", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться к списку номеров", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Apartments/Index.cshtml
@model IEnumerable<ARM_Hotel.Models.Apartment>

@{
    ViewBag.Title = "Номера";
}

<h2>Cписок номеров</h2>
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Добавить новый номер", "Create", null, new { @class = "btn btn-info" })
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxGuests)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxGuests)
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Operator"))
            {
                <td>
                    @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Добавить фото", "AddPhoto", new { id = item.Id }) |
                    @Html.ActionLink("Подробности", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                </td>

            }
            else
            {
                <td>
                    @Html.ActionLink("Подробности", "Details", new { id = item.Id })
                </td>
            }

        </tr>
    }

</table>